- name: Workflow Test
  hosts: localhost
  connection: local
  tasks:
    - name: Launch a workflow
      ansible.controller.workflow_launch:
      workflow_template: "Network Build Device Report"
    