---
- name: Print AWX Info 
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vault.yml
  vars:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"

  tasks:
    - debug:
        var: my_job_id
    
    - name: Get Node Results 
      ansible.builtin.uri:
        url: >-
          https://aap.shadowman.dev/api/controller/v2/jobs/{{ my_job_id }}/job_events
        method: GET
        headers:
          Authorization: "Bearer {{ aap_token }}"
        return_content: true
        validate_certs: false 
      delegate_to: localhost
      #no_log: true
      register: my_job_results
   
    - name: Print Job results
      debug:
        var: my_job_results.results.7.event_data.res.invocation.module_args
   
