---
- name: Play 1
  hosts: arista
  gather_facts: false
  tasks:
  vars:
    custom_hostname: basic
  
    - name: configure top level settings
      arista.eos.eos_config:
        lines: hostname {{ inventory_hostname }}-{{ custom_hostname }}
