---
- name: shut all instances
  hosts: localhost
  gather_facts: false
  tasks:
  
    - name: Terminate every running instance in a region. Use with EXTREME caution.
      amazon.aws.ec2_instance:
        region: us-east-2
        state: stopped
