---
- name: test aws vm connectivity
  hosts: all
  tasks:
    - name: debug
      debug: 
        msg: "{{ ansible_hostname }}"
      ignore_erros: yes 
13.58.62.32 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAHgITPY2EIkSvLBuSIihxgzlm7h3sQ3ZQv6JTe5zx0c
