---
##Used with networking workshop
- name: Router Hostname Demo
  hosts: cisco:arista
  gather_facts: no
  vars:
    custom_hostname: basic

  tasks:

    - name: Apply the provided configuration
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ custom_hostname }}"
        state: merged

    - name: Gather listed hostname config
      cisco.ios.ios_hostname:
        state: gathered
      register: hostnameinfo

    - name: Print output
      debug:
        var: hostnameinfo

- name: Router Hostname Demo
  hosts: arista
  gather_facts: no
  vars:
    custom_hostname: basic

  tasks:

    - name: Apply the provided configuration
      arista.eos.eos_hostname:
        config:
          hostname: "{{ custom_hostname }}"
        state: merged

    - name: Apply the provided configuration
      arista.eos.eos_hostname:
        config:
          hostname: "{{ custom_hostname }}"
        state: gathered
      register: hostnameinfo

    - name: Print output
      debug:
        var: hostnameinfo

- name: Router Hostname Demo
  hosts: juniper
  gather_facts: no
  vars:
    custom_hostname: basic

  tasks:

    - name: Apply the provided configuration
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ custom_hostname }}"
        state: merged

    - name: Apply the provided configuration
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ custom_hostname }}"
        state: gathered
      register: hostnameinfo

    - name: Print output
      debug:
        var: hostnameinfo