---
- name: Convert from Install to Bundle Mode
  hosts: cisco
  gather_facts: false
  vars:
    ansible_network_cli_ssh_type: paramiko
  tasks:
    - name: Remove Bin Files
      cisco.ios.ios_command:
        commands:
          - del /force c8000v*.bin

    - name: Fetch image to EE
      ansible.builtin.fetch:
        src: "/images/{{ upgrade_img }}"
        dest: /tmp/
        flat: true
      delegate_to: ansible-1
      run_once: true

    - name: Copy Image to device from EE
      ansible.netcommon.net_put:
        src: "/tmp/{{ upgrade_img }}"
        dest: "flash:/{{ upgrade_img }}"
      vars:
        ansible_command_timeout: 3000
        ansible_network_cli_ssh_type: paramiko

    # - name: Push new image from project to bootflash
    #   ansible.netcommon.net_put:
    #     src: /etc/ansible/c8000v-universalk9.17.07.01a.SPA.bin
    #     dest: c8000v-universalk9.17.07.01a.SPA.bin
    #   vars:
    #     ansible_command_timeout: 1000

    - name: Remove Bootvar
      cisco.ios.ios_config:
        commands:
          - no boot system
        save_when: always
    
    - name: Convert to Install Mode
      cisco.ios.ios_command:
        commands:
          - "install add file bootflash:{{ upgrade_img }} activate commit prompt-level none"
      vars:
        ansible_command_timeout: 1000

    # - name: Reload the Device
    #   ansible.netcommon.cli_command:
    #     command: reload
    #     prompt:
    #       - confirm
    #     answer:
    #       - "y"
    
    - name: Wait for device to come back online
      ansible.builtin.wait_for_connection:
        delay: 90
        timeout: 1000