---
- name: Convert from Install to Bundle Mode
  hosts: cisco
  gather_facts: false
  vars:
    ansible_network_cli_ssh_type: paramiko
  tasks:
    - name: Remove Install Mode Files
      cisco.ios.ios_command:
        commands:
          - del /force c8000v*.bin
          
    - name: Push new image from project to bootflash
      ansible.netcommon.net_put:
        src: /etc/ansible/c8000v-universalk9.17.06.06a.SPA.bin
        dest: flash:c8000v-universalk9.17.06.06a.SPA.bin
      vars:
        ansible_command_timeout: 1000

    - name: Change Bootvar
      cisco.ios.ios_config:
        commands:
          - no boot system
          - boot system bootflash:c8000v-universalk9.17.06.06a.SPA.bin
        save_when: always
    
    - name: Remove Install Mode Files
      cisco.ios.ios_command:
        commands:
          - del /force c8000v*.pkg
          - del /force packages.conf
    
    # - name: Reload the Device
    #   ansible.netcommon.cli_command:
    #     command: reload
    #     prompt:
    #       - confirm
    #     answer:
    #       - "y"
    - name: install new version from reboot
      cisco.ios.ios_command:
        commands: 
          - command: reload
            prompt: 'Proceed with reload\? \[confirm\]'
            answer: 'y'

    - name: Wait for device to come back online
      ansible.builtin.wait_for_connection:
        delay: 90
        timeout: 1000