---
- name: gather information from routers
  hosts: cisco
  gather_facts: no

  tasks:
    - name: gather router facts
      cisco.ios.facts:
        gather_subset: config
        #gather_network_resources: "{{ network_resource | default('!vlans') }}"
      register: myfacts

    - debug:
        var: myfacts