---
- name: gather information from routers
  hosts: cisco
  gather_facts: no

  tasks:
    - name: gather router facts
      cisco.ios.facts:
        gather_network_resources: all #"{{ network_resource | default('!vlans') }}"
      register: myfacts

    - name: Print Results
      debug:
        var: myfacts

    - name: Copy facts to a file 
      copy:
        content: "{{ myfacts | to_nice_yaml }}"
        dest: ./myfacts.txt