---
- name: Citrix remove host
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Setup server
      citrix.adc.citrix_adc_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        state: present
        name: 'dgdownload.shadowman.dev'
        ipaddress: 172.16.1.106
        validate_certs: false
      delegate_to: localhost
    
    - name: Setup service group and add host
      citrix.adc.citrix_adc_servicegroup:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        servicegroupname: dgreen-service-group-https
        maxclient: "4000"
        servicetype: TCP
        validate_certs: false
        servicemembers:
          mode: bind
          attributes:
            - servername: 'dgdownload.shadowman.dev'
              port: 443
              weight: "50"
        monitor_bindings:
          mode: exact
          attributes:
            - monitor_name: https
              weight: "50"
      delegate_to: localhost
