---
- name: Router Hostname Demo
  hosts: {{ router_name }}
  gather_facts: no

  tasks:

    - name: Change Router Hostname
      cisco.ios.config:
        commands:
          -  hostname {{ inventory_hostname }}-{{ custom_hostname }}
