---
- name:
  hosts: localhost
  gather_facts: no
  vars:
    dict1:
      key1: A
      key2: B
    dict2:
      key3: 1
      key4: 2
  tasks:
    - name:
      set_fact:
        # combined_dict: "{{ dict1 | combine(dict2) }}"
        combined_dict: "{{ dict(dict1|zip(dict2)) }}"
    - debug:
        var: combined_dict