---
- name: Meraki Play 1
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yml
    
  tasks:
   - name: Query all devices in a network.
     meraki_network:
       auth_key: "{{ auth_key }}"
       org_id: "{{ org_id }}"
       state: query
     register: merinfo
     delegate_to: localhost 
    
   - name: Use Debug Module to Print Results 
     debug:
       var: merinfo

   - name: Gather Network Name
     set_fact:
      network_name_id: "{{ merinfo.data | selectattr('name', 'equalto', 'again') | map(attribute='id') | list }}"   
       
   - debug:
       var: network_name_id