---
- name: Claim Devices
  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
    org_id: "{{ org_id }}"
    
  tasks:
  
    - name: Claim Devices to Network
      cisco.meraki.networks_devices_claim:
        meraki_api_key: "{{ meraki_key }}"
        networkId: "{{ dg_network_id }}"
        serials: 'Q2EV-QDJ4-LG23'
