---
- name: Get Network Id
  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
    org_id: "{{ org_id }}"
    
  tasks:
  
    - name: Get Network Info
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: my_network_info

    - name: Gather Network Name
      set_fact:
        my_network_id: "{{ my_network_info.meraki_response | selectattr('name', 'equalto', network_name ) | map(attribute='id') | list }}"

    - debug:
        msg: "{{ my_network_id | to_yaml }}"

    - name: Make Network Id Persistent
      ansible.builtin.set_stats:
        data:
          dg_network_id: "{{ my_network_id | to_yaml }}"
