---
- name: Test Communication to Meraki API
  hosts: localhost
  gather_facts: false
  var_files:
    - vault.yml
  tasks:
    
    - name: Add multiple syslog servers
      meraki_syslog:
        auth_key: "{{ auth_key }}"
        state: present #consider modifying logic to use absent state with no servers parameter
        org_id: "{{ org_id }}" 
        net_name: BigATL
        servers:
          - host:
      delegate_to: localhost	  
