---
- name: Test Communication to Meraki API
  hosts: localhost
  gather_facts: false
  tasks:
    
    - name: Calling Meraki Org Module to Query details
      meraki_organization:
        auth_key: {{ my_auth_key }} 
        state: query
        org_id: 253042
      register: merinfo
      delegate_to: localhost
     
    - name: Use Debug Module to Print Results 
      debug:
        var: merinfo
