---
- name: Test Communication to Meraki API
  hosts: localhost
  gather_facts: false
  tasks:
    
    - name: Calling Meraki Org Module to Query details
      meraki_organization:
        auth_key: "{{ auth_key }}"
        state: query
      register: merinfo
      delegate_to: localhost
     
    - name: Use Debug Module to Print Results 
      debug:
        var: merinfo
