---
- name: Test Communication to Meraki API
  hosts: localhost
  gather_facts: false
  tasks:
   - name: Query all devices in a network.
     meraki_device:
       auth_key: {{ my_auth_key }} 
       org_id: 253042
       state: query
     register: merinfo
     delegate_to: localhost 
    
   - name: Use Debug Module to Print Results 
     debug:
       var: merinfo
