---
- name: Modify Meraki configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault.yml
  tasks:

    - name: Block start
      block: 
        - name: Authorization Test
          debug:
            msg: ''
          failed_when: port_number > 24

        - name: Modify a switchport
          meraki_switchport:
            auth_key: "{{ auth_key }}"
            state: present
            serial: "{{ serial_number }}"
            enabled: "{{ port_status }}"
            number: "{{ port_number }}"
            name: "{{ port_name }}"
            vlan: "{{ vlan_number }}"
            type: "{{ port_type }}"
          delegate_to: localhost
          #when: port_number < 23
          

      rescue:
        - debug: 
            msg: "You ARE NOT authorized to modify port {{ port_number }}."
      
