---
- hosts: localhost
  vars:
   meraki_key: "{{ meraki_key }}"
   org_id: "{{ org_id }}"
  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "appliance" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'appliance') | list }}"
      register: network_id_get

    - name: Gather All Meraki Network Names
      set_fact:
        network_ids: "{{ filtered_networks | selectattr('id', 'defined') | map(attribute='id') | list }}"
    
    - name: Print
      debug:
        var: network_ids
    ############## Add tasks below
    