---
- name: Play 1
  gather_facts: false
  connection: local
  hosts: localhost

  vars_files:
    - vault.yml

  vars:
    base_url: "https://api.meraki.com/api/v1"
    meraki_headers:
      Content-Type: "application/json"
      X-Cisco-Meraki-API-Key: "{{ auth_key }}"


  tasks:

    - name: URI + Meraki Dashboard
      ansible.builtin.uri:
        url: "{{ base_url }}/organizations"
        method: GET
        headers: "{{ meraki_headers }}"
        follow_redirects: all
      register: meraki_info
      delegate_to: localhost

    - name: Change Camera Setting
      ansible.builtin.uri:
        url: "{{ base_url }}/devices/{{ serial_num }}/camera/qualityAndRetention"
        #don't forget to define serial number var in job template survey or somewhere else
        method: PUT
        headers: "{{ meraki_headers }}"
        follow_redirects: all
        body_format: json
        body:
          audioRecordingEnabled: false   
          quality: High
      delegate_to: localhost

    #- name:
      #debug:
        #var: meraki_info
      #delegate_to: localhost


          
        