---
- name: Meraki Play 1
  hosts: localhost
  gather_facts: false
  tasks:
   - name: Query all devices in a network.
     meraki_network:
       auth_key: KEY_HERE 
       org_id: 661615
       state: query
     register: merinfo
     delegate_to: localhost 
    
   - name: Use Debug Module to Print Results 
     debug:
       var: merinfo
