---
- hosts: leaf1
  gather_facts: true
  tasks:
  - name: Network Resource Manager
    ansible.builtin.include_role:
      name: network.base.resource_manager
    vars:
      operation: detect
      ansible_network_os: cisco.nxos.nxos
      resources:
        - 'hostname'
      data_store:
        local: "configs"