---
- name: Modify Palo Alto Firewall
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create address object
      paloaltonetworks.panos.panos_address_object:
        provider: 
          ip_address: "{{ talo_ip_address }}"
          username: "{{ talo_username }}"
          password: "{{ talo_password }}"
        name: '{{ object_name }}'
        address_type: 'ip-netmask'
        value: '{{ object_ip }}'

    - name: Create or modify object group
      paloaltonetworks.panos.panos_address_group:
        provider: 
          ip_address: "{{ talo_ip_address }}"
          username: "{{ talo_username }}"
          password: "{{ talo_password }}"
        name: 'BadGuys'
        static_value: "{{ object_name }}"
        state: 'merged'