---
- name: Check status of PAN FW 
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vault.yml 
  vars:
    # pre_object_name: []
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"

  tasks:

    - name: Attempt to create an object that already exists in the PAN FW. This should show as ok and no change.
      paloaltonetworks.panos.panos_address_object:
        provider: 
          ip_address: "{{ palo_ip_address }}"
          username: "{{ palo_username }}"
          password: "{{ palo_password }}"
        name: "Hacker 1"
        address_type: 'ip-netmask'
        value: 1.1.1.1

    - name: Attempt to create a net new object in the PAN FW. This should show changed.
      paloaltonetworks.panos.panos_address_object:
        provider: 
          ip_address: "{{ palo_ip_address }}"
          username: "{{ palo_username }}"
          password: "{{ palo_password }}"
        name: "Hacker 3"
        address_type: 'ip-netmask'
        value: 3.3.3.3
      #when: pre_object_name | length == 0

    # - name: Check if PAN-OS appliance is ready and wait until it is
    #   paloaltonetworks.panos.panos_check:
    #     provider: "{{ provider }}"
    #   changed_when: false
    #   register: result
    #   until: result is not failed and result.msg == 'Device is ready.'
    #   retries: 100
    #   delay: 15

    - name: Display output
      ansible.builtin.set_stats:
        data: 
          my_job_id: "{{ awx_job_id }}"
        per_host: false

