---
- name: Modify Palo Alto Firewall
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault.yml

  tasks:

    - name: Create address object
      paloaltonetworks.panos.panos_address_object:
        provider: 
          ip_address: "{{ inventory_hostname }}"
          username: "{{ palo_username }}"
          password: "{{ palo_password }}"
        name: '{{ object_name }}'
        address_type: 'ip-netmask'
        value: '{{ object_ip }}'

    - name: Create or modify object group
      paloaltonetworks.panos.panos_address_group:
        provider: 
          ip_address: "{{ palo_ip_address }}"
          username: "{{ palo_username }}"
          password: "{{ palo_password }}"
        name: 'BadGuys'
        static_value: "{{ object_name }}"
        state: 'merged'