---
- name: Aruba rest test
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather aruba facts
      arubanetworks.aoscx.aoscx_facts:
        gather_network_resources: software_version
      register: my_facts

    - name: Print output
      debug:
        msg: "{{ my_facts }}"
