---
- name: Aruba rest test
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather aruba facts
      arubanetworks.aoscx.aoscx_facts:
        gather_subset: platform_name 

    - name: Print output
      debug:
        msg: "{{ ansible_facts.net_mgmt_intf_status.hostname }},{{ ansible_facts.net_software_version }},{{ ansible_facts.net_platform_name }}"
