---
- name: Check to see if object already exists
  hosts: <palo fqdn>
  connection: local
  vars_files: ~/creds.yml
  vars:
    pre_object_name: []
    pre_group_name: []
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"

  tasks:
    - name:  Gather all objects
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        state: gathered
        gathered_filter: '*'
      register: all_pan_objects

    - name:  Gather all groups
      paloaltonetworks.panos.panos_address_group:
        provider: '{{ provider }}'
        state: gathered
        gathered_filter: '*'
      register: all_pan_groups

    - name: Gather info
      set_fact:
        filter_pan_groups: "{{ all_pan_groups.gathered | selectattr('static_value', 'contains', 'hacker2') | map(attribute='name') | list }}"   
      loop: "{{ all_pan_objects.gathered }}"
      when: item.value == object_ip
    - debug:
        var: filter_pan_groups