---
- name: Simple play to run a command
  hosts: cisco
  gather_facts: no

  tasks:
    - name: gather router facts
      cisco.ios.facts:

    - name: Issue commands to routers
      cisco.ios.ios_command:
        commands:
        - show run | i hostname
      register: command_output

    - name: Display prior command output
      debug:
        msg: The hostname was changed to {{ ansible_net_hostname }}
