---
- name: Switch Configuration
  hosts: switch1,switch2
  become: yes
  gather_facts: false
  tasks:
    - name: SNMP Config 
      cisco.ios.ios_snmp_server:
        config:
          communities:
            - name: READWRITE
              rw: yes
        state: deleted
      tags: snmp
     
    - name: VLAN Config
      cisco.ios.ios_vlans:
        config:
          - name: Data 
            vlan_id: 10
            state: active
          - name: Voice 
            vlan_id: 20
            state: active
          - name: Guest 
            vlan_id: 99
            state: active
        state: deleted
      tags: vlan		

    - name: Trunk Port Config 
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/3
            trunk:
              encapsulation: dot1q
        state: deleted     
      tags: trunk		
    
    - name: Trunk Port Config 
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/3
        state: deleted      
      tags: trunk

    - name: Remove SVI
      cisco.ios.ios_interfaces:
        config:
          - name: Vlan20
        state: purged      
      tags: trunk
    # - name: Raw Commands 
    #   cisco.ios.ios_config:
    #     lines:
    #       - no interface Vlan20
        


