---
- name: Template Test
  hosts: cisco
  gather_facts: no
  tasks:
    - name: 
      ansible.builtin.template:
        src: ~/lab/switch_template.j2
        dest: ~/lab/{{ inventory_hostname }}_routerconfig.txt
      delegate_to: localhost
  
