---
- name: Verbosity test
  hosts: localhost
  tasks:
    - name: modify ansible.cfg file 
      lineinfile:
        path: /etc/ansible.ansible.cfg 
        insertafter: '^\[defaults\]$'
        line: verbosity=4