---
- name: Configure Junos Device
  hosts: juniper
  gather_facts: no
  tasks:
    - name: Modify Device Hostname
      junipernetworks.junos.junos_hostname:
        config:
          hostname: "{{ inventory_hostname }}"