- name: Rules with kafka as source
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        topic: network
        host: kafka.shadowman.dev
        port: 9092

  rules:
    - name: Fix Down Port
      condition: events.body.fields.new_state == "interface-notif-state-down"
      action:
        run_job_template:
          name: "ciscoeda"
          organization: Security
          job_args:
            extra_vars:
              interface: "{{ event.body.fields.if_name }}"
              rtr: "{{ event.body.fields.host_name }}"