- name: Rules with kafka as source
  hosts: localhost 
  sources:
    - ansible.eda.webhook:
        port: 5000 

  rules:
    - name: Test rule 
      condition: event.payload.severity == critical
      action:
        run_job_template: 
          name: "Basic Command"
          organization: Default