---
- name: Play1 
  hosts: servera.lab.example.com 
  vars:
    fw_pkg: firewalld
    fw_svc: firewalld
    w_pkg: httpd
    w_svc: httpd
    ssl_pkg: mod_ssl
    httpdconf_src: files/httpd.conf
    httpdconf_dest: /etc/httpd/conf/httpd.conf
    htaccess_src: files/.htaccess
    secrets_dir: /etc/httpd/secrets
    secrets_src: files/htpasswd
    secrets_dest: "{{ secrets_dir }}/htpasswd"
    web_root: /var/www/html

  tasks:

    - name: Install Packages
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - "{{ fw_pkg }}"
        - "{{ w_pkg }}"
        - "{{ ssl_pkg }}"
      tags: works

    - name: Add secrets file
      copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_dest }}"
        owner: root
        group: root
        mode: 0644
      tags: works

    - name: Create secrets directory
      file:
        state: directory
        path: "{{ secrets_dir }}"
        group: apache
        owner: apache
        mode: 0500
      tags: works
    
    - name: Copy file to secrets directory 
      copy:
        src: "{{ secrets_src }}"
        dest: " { secrets_dest }}"
        mode: 0400
        owner: apache
        group: apache
      tags: works

    - name: Copy more files
      copy: 
        src: "{{ htaccess_src }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: 0400
      tags: works

    - name: Create index html file
      copy:
        content: "{{ ansible_facts['fqdn'] }}({{ ansible_facts['default_ipv4']['address'] }}) has been customized by Ansible."
        dest: "{{ web_root }}/index.html"
      tags: works

    - name: Start firewalld 
      service: 
        name: "{{ fw_svc }}"
        state: started
        enabled: true 
      tags: works

    - name: Allow http
      firewalld:
        service: https
        permanent: true
        immediate: true
        state: enabled
      tags: works

    - name: Start apache
      service: 
        name: "{{ w_svc }}"
        state: started
        enabled: true 
      tags: works

- name: Play 2
  hosts: localhost
  become: false
  vars:
    - web_user: guest

  vars_files:
    - vars/secret.yml

  tasks:

    - name: Use URI module
      uri:
        url: https://servera.lab.example.com
        status_code: 200
        user: "{{ web_user }}"
        password: "{{ web_pass }}"
        validate_certs: false
        force_basic_auth: true
        return_content: true
      register: auth_var

    - name: Print output
      debug:
        var: auth_var