---
- name: Playbook Control Lab
  hosts: webservers
  vars_files: vars.yml
  tasks:
    #Fail Fast Message
    - name: Fail Message
      fail:
        msg: "This task failed."
      when: ansible_facts['memory_mb']['real']['total'] < min_ram_mb or ansible_facts['distribution'] != 'RedHat'
    
    #Install all Packages
    - name: Ensure required packages are present
      yum:
        name: "{{ packages }}"
        state: latest

    #Enable and start services
    - name: Start all services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ services }}"

    #Block of config tasks
    - name: Task block
      block:
        - name: Create directory
          file:
            state: directory
            path: /etc/httpd/conf.d/ssl

        - name: Copy files
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ web_config_files }}"
          notify: restart web service

      rescue:
        - name: Post failure message
          debug:
            msg: One or more of the configuration changes failed, but the web service is still active.

    #Configure the firewall
    - name: Allow http and https
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      loop:
        - http
        - https
  
  #Add handlers
  handlers:
    - name: restart web service
      service:
        name: "{{ web_service }}"
        state: restarted